'use client';
import { useState, type FormEvent } from 'react';
import { MapPin, Shield, Users, Target, Menu, X, CheckCircle, Mail } from 'lucide-react';
function ClubMark(){return <span className="club-mark">JU<span>CC</span></span>}
type EnquiryKind = 'contact' | 'recruitment' | 'friendly' | 'partnership';
function EnquiryForm({kind,setKind}:{kind:EnquiryKind;setKind:(kind:EnquiryKind)=>void}){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fields=Object.fromEntries(new FormData(form));setState('sending');try{const res=await fetch('https://formsubmit.co/ajax/njerseyunited@gmail.com',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({...fields,kind,consent:fields.consent==='on',_subject:`Jersey United CC — ${kind==='recruitment'?'Player recruitment':kind==='friendly'?'Friendly match':kind==='partnership'?'Partnership / sponsorship':'General enquiry'}`,_replyto:fields.email,_template:'table',_captcha:'false',_honey:fields.website,_url:window.location.origin})});const data=await res.json() as {success?:boolean|string;message?:string;error?:string};if(!res.ok||(data.success!==true&&data.success!=='true'))throw new Error(data.message||data.error||'We couldn’t send your message. Please try again.');setState('success');form.reset();}catch(e){setError(e instanceof Error?e.message:'Please try again.');setState('error');}}
 if(state==='success')return <div className="success" role="status"><CheckCircle size={40}/><h3>{kind==='recruitment'?'You’re on our radar.':'Thanks for reaching out.'}</h3><p>Your {kind==='recruitment'?'player interest':'message'} has been submitted. The club can contact you using the details you provided.</p><button className="button secondary" onClick={()=>setState('idle')}>Send another submission</button></div>;
 return <form onSubmit={submit}><div className="form-grid"><label className="wide">What are you contacting us about?<select name="kind" value={kind} onChange={e=>setKind(e.target.value as EnquiryKind)} required><option value="contact">General enquiry</option><option value="recruitment">Player recruitment</option><option value="friendly">Friendly match</option><option value="partnership">Partnership / sponsorship</option></select></label><label>Full name<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Your full name"/></label><label>Email address<input name="email" autoComplete="email" type="email" required maxLength={254} placeholder="you@example.com"/></label>{kind==='recruitment'&&<><label>Phone <span>(optional)</span><input name="phone" autoComplete="tel" type="tel" maxLength={40} placeholder="Your phone number"/></label><label>Playing role<select name="role" required defaultValue=""><option value="" disabled>Select your role</option>{['Batter','Bowler','All-rounder','Wicketkeeper'].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Cricket experience<select name="experience" required defaultValue=""><option value="" disabled>Select your experience</option>{['New to cricket','Club experience','Competitive league experience'].map(x=><option key={x}>{x}</option>)}</select></label></>}<label className="wide">{kind==='recruitment'?'Tell us about your game':'Your message'}<textarea name="message" rows={4} required minLength={5} maxLength={3000} placeholder={kind==='recruitment'?'Your playing background, availability, and what you’re looking for…':kind==='friendly'?'Your team name, preferred dates, format, and location…':kind==='partnership'?'Tell us about your organisation and partnership idea…':'How can we help?'}/></label></div><label className="trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input type="checkbox" name="consent" required/>I agree to Jersey United contacting me about this enquiry.</label><p className="privacy-note">Your details are processed by FormSubmit to email your enquiry to the club. They are not displayed publicly.</p>{state==='error'&&<p role="alert" className="error">{error}</p>}<button disabled={state==='sending'} className="button">{state==='sending'?'Sending…':kind==='recruitment'?'Submit player interest':'Send message'}</button></form>
}
export default function Home(){const[menu,setMenu]=useState(false);const[kind,setKind]=useState<EnquiryKind>('contact');return <>
<header className="header"><a href="#home" className="brand" aria-label="Jersey United home"><ClubMark/><span>JERSEY UNITED<small>CRICKET CLUB</small></span></a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''} aria-label="Main navigation">{[['About us','about'],['The club','club'],['Contact','contact']].map(([t,id])=><a key={id} onClick={()=>{setMenu(false);if(id==='contact')setKind('contact');}} href={'#'+id}>{t}</a>)}<a className="button" onClick={()=>{setMenu(false);setKind('recruitment');}} href="#contact">Join the club</a></nav></header>
<main><section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">NEW JERSEY. ONE TEAM.</p><h1>Different stories.<br/>One <em>United.</em></h1><p className="hero-description">A shared love of cricket. A team to call your own. Jersey United brings players together to build something bigger than the game.</p><div className="hero-actions"><a className="button" href="#contact" onClick={()=>setKind('recruitment')}>Play with Jersey United</a><a className="text-link" href="#about">Discover our club</a></div><div className="hero-location"><MapPin size={17}/> New Jersey, USA <span>•</span> Cricket. Community. Commitment.</div></div><div className="hero-photo" role="img" aria-label="Cricket bat and ball on a green cricket ground"><div className="photo-label"><span>THE GAME BRINGS US TOGETHER</span><strong>The team keeps us here.</strong></div></div></section>
<div className="values-strip"><span>PLAY WITH PURPOSE</span><span>RESPECT THE GAME</span><span>GROW TOGETHER</span><span>JERSEY UNITED CC</span></div>
<section className="section about" id="about"><div><p className="eyebrow">01 / ABOUT JERSEY UNITED</p><h2>A local club.<br/>A shared ambition.</h2></div><div className="about-copy"><p className="lead">We’re building a cricket community in New Jersey, united by teamwork, respect, and a genuine passion for the sport.</p><p>Jersey United is a place for players who want to contribute, improve, and enjoy the game together. Whether you bring years of league experience or are looking for your next team, we’d love to hear your story.</p><a href="#contact" onClick={()=>setKind('recruitment')} className="text-link">Find your place in the team</a></div></section>
<section id="club" className="club section"><div className="section-heading"><div><p className="eyebrow">02 / WHAT WE STAND FOR</p><h2>More than a match day.</h2></div><p>Good cricket starts with a good team.<br/>Here’s the spirit we bring to the field.</p></div><div className="cards">{[[Users,'A team-first mindset','Support your teammates, celebrate the small wins, and play your part. Everyone brings something to the XI.'],[Target,'Room to improve','Bring your commitment and curiosity. We value effort, honest feedback, and the drive to get better.'],[Shield,'Respect, always','For the opposition, the officials, and the game. Competitive cricket and good sportsmanship belong together.']].map(([Icon,title,description],i)=>{const C=Icon as typeof Users;return <article key={i}><div className="card-top"><C size={28}/><span>0{i+1}</span></div><h3>{String(title)}</h3><p>{String(description)}</p></article>})}</div></section>
<section id="contact" className="section contact"><div><p className="eyebrow">03 / JOIN & GET IN TOUCH</p><h2>Let’s talk cricket.</h2><p>Want to play with Jersey United, arrange a friendly match, or explore a partnership? Choose an enquiry type and tell us more.</p><div className="contact-detail"><MapPin/><div><strong>Based in New Jersey</strong><span>United by cricket.</span></div></div><div className="contact-detail"><Mail/><div><strong>Contact the club</strong><span>Use the form to reach Jersey United.</span></div></div><details><summary>Where and when do you play?</summary><p>Match locations and schedules will be shared when confirmed. Contact us for the latest club information.</p></details><details><summary>Can I enquire about a friendly match?</summary><p>Yes. Include your team name, preferred dates, format, and location in your message.</p></details></div><div className="form-card"><h3>One club. Let’s connect.</h3><p>Select your enquiry type to get started.</p><EnquiryForm kind={kind} setKind={setKind}/>{kind==='recruitment'&&<p className="fine">Submitting interest does not guarantee a place on the team.</p>}</div></section></main>
<footer><div className="brand"><ClubMark/><span>JERSEY UNITED<small>CRICKET CLUB</small></span></div><p>Different stories. One United.</p><div><a href="#about">About</a><a href="#contact" onClick={()=>setKind('recruitment')}>Join</a><a href="#contact">Contact</a></div><small>© {new Date().getFullYear()} Jersey United Cricket Club</small></footer></>}
